{% set name = "harlequin" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/harlequin-{{ version }}.tar.gz
  sha256: e991ada24ddfcbf5409af3100f95f29aad7dd7e33dcb0ae833d0078a19a78c41

build:
  entry_points:
    - harlequin = harlequin.cli:harlequin
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - python-duckdb >=0.8.0
    - questionary >=2.0.1,<3.0.0
    - tomli >=2.0.1,<3.0.0
    - tomlkit >=0.12.5,<0.14.0
    - rich-click >=1.7.1,<2.0.0
    - importlib-metadata >=8.0
    - python >={{ python_min }},<4.0.0
    - textual ==0.89.1
    - textual-fastdatatable ==0.12.0
    - textual-textarea ==0.15.0
    - click >=8.1.3,<9.0.0
    - shandy-sqlfmt >=0.19.0
    - platformdirs >=3.10,<5.0
    - numpy >=2.0.0,<2.1.0

test:
  imports:
    - harlequin
  commands:
    - pip check
    - harlequin --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://harlequin.sh
  dev_url: https://github.com/tconbeer/harlequin
  summary: The DuckDB IDE for Your Terminal.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - xhochy
