{% set name = "harlequin" %}
{% set version = "1.22.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harlequin-{{ version }}.tar.gz
  sha256: b18e1d9f55ee26ff23c60a9867a8e107271e8f8ff6efe55d84b00b75d279ce36

build:
  entry_points:
    - harlequin = harlequin.cli:harlequin
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - python-duckdb >=0.8.0
    - questionary >=2.0.1,<3.0.0
    - tomli >=2.0.1,<3.0.0
    - tomlkit >=0.12.3,<0.13.0
    - rich-click >=1.7.1,<2.0.0
    - importlib-metadata >=4.6.0
    - textual-fastdatatable ==0.7.1
    - python >=3.8.0,<4.0.0
    - textual ==0.56.4
    - textual-textarea ==0.13.0
    - click >=8.1.3,<9.0.0
    - shandy-sqlfmt >=0.19.0
    - platformdirs >=3.10,<5.0
    - numpy <2.0.0

test:
  imports:
    - harlequin
  commands:
    - pip check
    - harlequin --help
  requires:
    - pip

about:
  home: https://harlequin.sh
  dev_url: https://github.com/tconbeer/harlequin
  summary: The DuckDB IDE for Your Terminal.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - moritzwilksch
    - xhochy
