{% set name = "harlequin" %}
{% set version = "1.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/harlequin-{{ version }}.tar.gz
  sha256: da830c1944d9dca7ac1f31b9dab8fa7d6a3acef11376103193908516053bb381

build:
  entry_points:
    - harlequin = harlequin.cli:harlequin
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - poetry-core
    - pip
  run:
    - duckdb >=0.8.0
    - importlib-metadata >=4.6.0
    - textual-fastdatatable ==0.1.4
    - python >=3.8.0,<4.0.0
    - textual ==0.40.0
    - textual-textarea ==0.7.3
    - click >=8.1.3,<9.0.0
    - python-duckdb >=0.8.0
    - shandy-sqlfmt >=0.19.0
    - platformdirs >=3.10.0,<4.0.0
    - pyperclip >=1.8.2,<2.0.0

test:
  imports:
    - harlequin
  commands:
    - pip check
    - harlequin --help
  requires:
    - pip

about:
  home: https://harlequin.sh
  summary: The DuckDB IDE for Your Terminal.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
