schema_version: 1

context:
  name: harlequin
  version: 2.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/harlequin-${{ version }}.tar.gz
  sha256: d8489bea2a2d466c9b1e4f1499cddc8a996d15b868f9d76493ca8c051e6ec9ec

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - harlequin = harlequin.cli:harlequin

requirements:
  host:
    - python ${{ python_min }}
    - hatchling
    - pip
  run:
    - tree-sitter-sql ==0.3.7
    - tree_sitter >=0.23.0,<0.25.0
    - python-duckdb >=0.8.0
    - questionary ==2.0.1
    - tomli >=2.0.1,<3.0.0
    - tomlkit >=0.12.5,<0.14.0
    - rich-click ==1.8.5
    - importlib-metadata >=8.0
    - python >=${{ python_min }}
    - textual ==0.89.1
    - textual-fastdatatable ==0.12.0
    - textual-textarea ==0.15.0
    - click ==8.1.8
    - shandy-sqlfmt >=0.19.0
    - platformdirs >=3.10,<5.0
    - numpy >=2.0.0,<2.3.0

tests:
  - python:
      imports:
        - harlequin
  - requirements:
      run:
        - pip
        - python ${{ python_min }}
    script:
      - pip check
      - harlequin --help

about:
  summary: The DuckDB IDE for Your Terminal.
  license: MIT
  license_file: LICENSE
  homepage: https://harlequin.sh
  repository: https://github.com/tconbeer/harlequin

extra:
  recipe-maintainers:
    - moritzwilksch
    - xhochy
